export default{
    data(){
        return{
            es :{
                welcomeMsg:"Hola, yo soy José Tabares",
                cuerpoFirstMessage:"Soy ingeniero de software con una pasión por las arquitecturas escalables y las tecnologías emergentes. Actualmente trabajo como desarrollador full stack en un centro de investigación de la Universidad de Sevilla llamado Fidetia, donde también trabajo en proyectos de Inteligencia Artificial, una materia a la que me gustaría dedicarme en el futuro.",
                cuerpoSecondMessage:"Me encanta trabajar en equipo para resolver problemas. Siempre pensamos que nuestras contribuciones pueden tener un significado para otras personas. Fuera del trabajo, es probable que me encuentres leyendo libros, jugando videojuegos o haciendo ejercicio.",
                cuerpoThirdMessage:"Me apasiona hablar con gente nueva sobre tecnología, aprender cosas nuevas y soy muy ambicioso. Si tienes alguna pregunta, no dudes en ponerte en contacto conmigo. A continuación, puedes ver algunas de mis habilidades tecnológicas que he adquirido a lo largo de los años.",
                clickMe:"clickéame!!",
                mySkills:"Mis habilidades",
                cambiaIdioma:"cambia el idioma",
                contentPython:`Con más de 2 años de experiencia en Python, he adquirido habilidades en diversos dominios, incluyendo el desarrollo web y la inteligencia artificial. He navegado con destreza los frameworks Flask y Django, aprovechando sus potentes características para construir aplicaciones web robustas y escalables. Desde la creación de elegantes APIs RESTful hasta el diseño de sistemas backend complejos, Python ha sido uno de mis lenguajes favoritos para desarrollar soluciones eficientes y mantenibles.\rMás allá del desarrollo web, Python ha sido fundamental en mi incursión en el reino de la inteligencia artificial. Aprovechando su sistema de librerías como NumPy, Pandas y TensorFlow, he desarrollado sofisticados modelos de aprendizaje automático y aprendizaje profundo. Desde el análisis predictivo hasta las tareas de procesamiento de lenguaje natural, la versatilidad y expresividad de Python me han permitido abordar diversos desafíos en el campo de la inteligencia artificial.\rComo desarrollador Python experimentado, me apasiona superar los límites de lo que es posible con este lenguaje tan versátil. Mi experiencia práctica en la construcción de proyectos utilizando Flask y Django, junto con mi experiencia en el uso de Python para aplicaciones de inteligencia artificial, me posiciona como un profesional versátil e innovador listo para asumir nuevos y emocionantes desafíos en el panorama tecnológico en constante evolución. Ya sea para arquitecturizar aplicaciones web escalables o profundizar en la investigación de vanguardia en IA, estoy comprometido a ofrecer resultados excepcionales que impulsen el valor y la innovación.`,
                contentjs:`Poseo más de 2 años de experiencia trabajando con JavaScript en una variedad de proyectos, incluyendo aplicaciones web, aplicaciones móviles y backends. Tengo un fuerte conocimiento de los fundamentos de JavaScript, así como de las últimas tecnologías y frameworks.\rEn mi experiencia, he utilizado JavaScript para desarrollar aplicaciones web robustas y escalables, utilizando frameworks como Vue.js para crear interfaces de usuario interactivas y atractivas. También he trabajado con Node.js para crear backends eficientes y escalables, y he integrado JavaScript con diferentes bases de datos, como MySQL y MongoDB.\rAdemás de mi experiencia en desarrollo web, también he trabajado en la implementación de modelos de IA en aplicaciones web. Tengo experiencia en el uso de bibliotecas de JavaScript como TensorFlow.js para integrar modelos de aprendizaje automático y aprendizaje profundo que se pueden ejecutar directamente en el navegador web.`,
                contentvue:`Podría decir que tengo más de 2 años de experiencia profesional utilizando Vue.js, tanto en proyectos personales profesionales, como proyectos de diferentes trabajos. Vue.js es mi framework JavaScript favorito y lo he utilizado para construir una variedad de aplicaciones web. Soy experto en todos los aspectos del framework Vue.js, incluida la biblioteca central, Vuex, Vue Router y Vuetify. También estoy familiarizado con las mejores prácticas para el desarrollo full-stack, como diseño responsivo, pruebas unitarias y optimización del rendimiento.\rAdemás de mi experiencia profesional, también he estado utilizando Vue.js para proyectos personales durante más de 4 años. Esto me ha dado la oportunidad de experimentar con diferentes características del framework y aprender de mis errores. Confío en mi capacidad para usar Vue.js para construir aplicaciones web de alta calidad y fáciles de usar.\r De hecho, esta web está creada usando Vue, junto a Three.js para gestionar la escena, la cual está creada usando Blender para el modelo.`,
                contentai:`Como mencioné anteriormente, soy experto en varios frameworks de Python para el desarrollo de inteligencia artificial, como:\r-TensorFlow\r-Scikit-learn\r-Pandas (Aunque Pandas no es específicamente para IA, se usa mucho para el manejo de datos necesario para construir modelos)\r-Keras\rTengo una amplia experiencia en el uso de estos frameworks para construir una variedad de modelos de IA, incluyendo:\r-Redes neuronales\r-Árboles de decisión\r-K-Vecinos más cercanos (KNN)\rCuento con más de 2 años de experiencia profesional en el desarrollo de IA. En mi puesto anterior, fui responsable de desarrollar e implementar modelos de IA para mejorar la eficiencia de nuestras operaciones comerciales. También he trabajado en varios proyectos académicos relacionados con la IA, que incluyen:\rDesarrollar una red neuronal para predecir la cantidad de litros de aceite en la industria aceite.\rConstruir un árbol de decisión para clasificar imágenes.\rImplementar un algoritmo K-Vecinos más cercanos (KNN) para la recomendación de productos.\rUtilizar la librería OpenCV para desarrollar un sistema que pueda leer los ojos y predecir hacia dónde miran.\rConfío en mi capacidad para usar la IA para resolver problemas del mundo real. Siempre estoy buscando nuevos desafíos y oportunidades para aplicar mis habilidades y conocimientos.`,
                contentothers:`-Bases de datos:\rPoseo experiencia en el uso de bases de datos SQL y MongoDB. Durante mi carrera universitaria, adquirí un sólido conocimiento en SQL a través de diversos cursos y proyectos académicos. Esta formación me permitió comprender los fundamentos de las bases de datos relacionales, incluyendo la creación de estructuras de datos, la gestión de información y la realización de consultas complejas.\rEn el ámbito profesional, he trabajado con MongoDB durante un par de años. Esta experiencia me ha permitido familiarizarme con las características específicas de este tipo de bases de datos NoSQL, como la flexibilidad en el almacenamiento de datos y la escalabilidad horizontal. He utilizado MongoDB para el desarrollo de aplicaciones web, la gestión de documentos y la analítica de datos.\rA continuación, se detallan algunos ejemplos específicos de mi experiencia:\r
SQL:\r*Diseño e implementación de bases de datos relacionales para proyectos académicos.\r*Realización de consultas complejas para extraer información relevante de las bases de datos.\r*Optimización del rendimiento de las consultas SQL.\rMongoDB:\r*Desarrollo de aplicaciones web que utilizan MongoDB como base de datos.\r*Implementación de esquemas de datos NoSQL para optimizar la flexibilidad y escalabilidad.\r*Realización de consultas y análisis de datos en MongoDB.-Docker:\rDurante mi formación académica, tuve la oportunidad de adquirir experiencia con Docker. Esta experiencia se desarrolló en el contexto de diferentes cursos y proyectos, donde se utilizó Docker para:\rContenerizar aplicaciones: Implementé aplicaciones web y de escritorio en contenedores Docker, lo que me permitió aislarlas del entorno y facilitar su portabilidad y escalabilidad.\rCrear entornos de desarrollo replicables: Utilicé Docker para crear entornos de desarrollo idénticos para cada miembro de un equipo, lo que facilitó la colaboración y la reproducibilidad de los resultados.\rAutomatizar tareas de DevOps: Implementé flujos de trabajo de DevOps utilizando Docker para automatizar tareas como la construcción, la integración y la implementación de aplicaciones.\r-GitHub: 4 años de carrera y 2 años profesionales\rPoseo una amplia experiencia en el uso de GitHub, que abarca 4 años de mi carrera universitaria y 2 años de trabajo profesional. Durante este tiempo, he utilizado GitHub para una variedad de propósitos tanto personales como profesionales.\r-Otros:\rDurante mi experiencia además de los ya mencionados he trabajado en otros proyectos con diferentes lenguajes como C, C# o C++, sin embargo, no he trabajado directamente de manera profesional en estos campos, no lo descartaría en un futuro\r`,
                contentjava:`Poseo una amplia experiencia en el desarrollo con Java, la cual abarca 4 años de mi carrera universitaria. A lo largo de este tiempo, he adquirido un sólido conocimiento de las características y funcionalidades del lenguaje, utilizándolo en una variedad de proyectos y contextos.\r-Conocimientos y habilidades:\r*Desarrollo web: He utilizado Java para el desarrollo de aplicaciones web dinámicas utilizando servlets, frameworks como Spring y JSP.\r*Integración de modelos: Tengo experiencia en la integración de modelos de machine learning, como H2O, en aplicaciones Java.\r*Algoritmos: He desarrollado de manera autodidacta algoritmos personalizados en Java, como árboles de decisión y algoritmos de recursividad.\r-Ejemplos de proyectos:\rAplicación web de búsqueda de hoteles: Desarrollé una aplicación web completa utilizando Java, Spring y MySQL para la búsqueda de hoteles y eventos en una ciudad concreta.\rSistema veterinario: Implementé un sistema de agendado de citas y almacenamiento de clientes en una base de datos usando JAVA.`,
                titleMyskills:`Conóceme un poco mas!`,
                contentSkills:`Hey, soy yo, si quieres saber un poco más de mi, pincha en las tecnologías de la pared`,
                leftSideContent:"Uso y programo IA",
                rigthSideContent:"Disfruto el desarrollo web al máximo",
                ADeveloper:"UN DESARROLLADOR",
                IAmJoseTabares:"SOY TABARES",
                adjustableText:"¡Bienvenidos a mi página! Soy José, tengo alrededor de 3 años como programador. Si quieren conocerme más, hagan clic justo arriba, en mi lado creativo."
                
            }
        }
    }
}